name: "Nuxt Generate"

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  # Allows external webhook trigger
  repository_dispatch:
        types:
          - webhook
env:
  API_ENDPOINT: "${{ vars.CMS_API_ENDPOINT }}"
  CDN_URL: "${{ vars.CDN_URL }}"
  ASSETS_BASEURL: "${{ vars.ASSETS_BASEURL }}"
  GTM_ID: "${{ vars.GTM_ID }}"

jobs:
  generate-static-html:
    name: Generate static HTML files
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/scj2000/scj2000-web-v2/scj2000-web:latest
          options: >
            -v ${{ github.workspace }}:/frontend/.output/
            -e API_TOKEN="${{ secrets.CMS_API_TOKEN }}"
            -e API_ENDPOINT="${{ env.API_ENDPOINT }}"
            -e CDN_URL="${{ env.CDN_URL }}"
            -e ASSETS_BASEURL="${{ env.ASSETS_BASEURL }}"
            -e GTM_ID="${{ env.GTM_ID }}"
          run: npm run regenerate
      - name: Add and commit generated HTML
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "scj2000 content update"
          author_email: "webmaster@scj2000.net"
          message: "Content update $NOW"
          cwd: ${{ github.workspace }}
          push: true
          new_branch: test
        